### ISSUE TITLE
Constant STATE already defined

### ISSUE THREAD

**Issue by simon-pipe** [GiovanniSalmeri/yellow-mailer#3]
Hi Giovanni

I have installed your plugin and get the following message. Unfortunately I can't find a solution myself. Thank you if you can help me.

**Error**
Warning: Constant STATE already defined in /var/www/html/system/workers/mailer.php on line 257

Warning: Constant STATE already defined in /var/www/html/system/workers/mailer.php on line 257

Fatal error: Uncaught TypeError: array_walk_recursive(): Argument #1 ($array) must be of type array, null given in /var/www/html/system/workers/mailer.php:447 Stack trace: #0 /var/www/html/system/workers/mailer.php(447): array_walk_recursive(NULL, Object(Closure)) #1 /var/www/html/system/workers/mailer.php(312): YellowMailer->sanitise(Array) #2 /var/www/html/system/workers/mailer.php(209): YellowMailer->send(Array, false, true) #3 /var/www/html/system/workers/core.php(2933): YellowMailer->onMail('contact', Array, 'Du hast eine Na...') #4 /var/www/html/system/workers/contact.php(105): YellowToolbox->mail('contact', Array, 'Du hast eine Na...') #5 /var/www/html/system/workers/contact.php(49): YellowContact->sendMail() #6 /var/www/html/system/workers/core.php(3227): YellowContact->onParsePageLayout(Object(YellowPage), 'contact') #7 /var/www/html/system/workers/core.php(3187): YellowPage->parsePageLayout('contact') #8 /var/www/html/system/workers/core.php(196): YellowPage->parsePage() #9 /var/www/html/system/workers/core.php(142): YellowCore->sendPage('https', 'XXXX', '', '/contact/', 'content/contact...', true, true) #10 /var/www/html/system/workers/core.php(113): YellowCore->processRequest('https', 'XXXX', '', '/contact/', 'content/contact...', true) #11 /var/www/html/yellow.php(9): YellowCore->request() #12 {main} thrown in /var/www/html/system/workers/mailer.php on line 447

**yellow-system.ini:**
MailerSender: XXXX
MailerTransport: smtp
MailerSendmailPath: /usr/sbin/sendmail
MailerSmtpServer: in-v3.mailjet.com
MailerSmtpSecurity: ssl
MailerSmtpUsername: XXXX
MailerSmtpPassword: XXXX
MailerAttachmentDirectory: media/attachments/

**Comment by GiovanniSalmeri** [comment]
Thank you very much, I will look into this problem as soon as possible.

**Comment by GiovanniSalmeri** [comment]
I have updated the extension, could you try with this new version? Thank you very much!

**Comment by simon-pipe** [comment]
The mistake is gone. Thank you very much for the quick answer.

Now there's something wrong with my configuration. 

> Serverfehler
> Etwas ist schief gelaufen. Nachricht konnte nicht versandt werden, versuche es später erneut!

**Comment by simon-pipe** [comment]
I can't get the plugin to work. I always get the following error message:

> error Mailer: ["headers"]["from"]: Ungültige E-Mail Adresse

But I have set up the same settings for SMTP including port on other devices and there you go. Could it be that the plugin has another error?

I have already checked the Sendmail path.

**Comment by GiovanniSalmeri** [comment]
I will check he plugin as soon as possible. Sorry for the trouble!

**Comment by simon-pipe** [comment]
Have you ever been able to look?

**Comment by simon-pipe** [comment]
After the last update everything is running perfectly. Thank you very much!
